// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkqvbrglxhhpqxirtija.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrcXZicmdseGhocHF4aXJ0aWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjU1MzgsImV4cCI6MjA2NDcwMTUzOH0.z6jbFoJtbFT-WjXwt3TqJsxPSJNAFm4auz8y-BzcFWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});